In [1]:
import numpy as np

In [2]:
# Array 1D

d1 = np.array([1,2,3])
print(d1)

[1 2 3]


In [4]:
d1.shape

(3,)

In [5]:
d1.ndim

1

In [6]:
d1.dtype

dtype('int32')

In [7]:
# Array 2D

d2 = np.array([[1,2,3], [4,5,6]])
print(d2)

[[1 2 3]
 [4 5 6]]


In [8]:
d2.shape

(2, 3)

In [10]:
d2.ndim

2

In [13]:
d2.dtype

dtype('int32')

In [28]:
# Array 3D

d3 = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(d3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
d3.shape

(2, 2, 2)

In [30]:
d3.ndim

3

In [31]:
d3.dtype

dtype('int32')

In [4]:
A = np.array([2, 3, 4])
B = np.array([2, 3, 4])

result = np.add(A,B)
print(result)

[4 6 8]


In [5]:
C = np.array([[2, 4, 6, 8], [1, 3, 5, 7]])
print(C)

[[2 4 6 8]
 [1 3 5 7]]


In [8]:
C[0,-1]

8

In [11]:
C[1,:]

array([1, 3, 5, 7])

In [12]:
C[:,1]

array([4, 3])